Controllers/CreditCardsController.cs
using CreditCards.Data;
using CreditCards.Models;
using CreditCardValidator;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CreditCards.Controllers
{
    public class CreditCardsController : Controller
    {
        private readonly CreditCardsContext _context;

        public CreditCardsController(CreditCardsContext context)
        {
            _context = context;
        }

        // GET: CreditCards
        public async Task<IActionResult> Index()
        {
            return _context.CreditCard != null ?
                        View(await _context.CreditCard.ToListAsync()) :
                        Problem("Entity set 'CreditCardsContext.CreditCard'  is null.");
        }

        // GET: CreditCards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CreditCard == null)
            {
                return NotFound();
            }

            var creditCard = await _context.CreditCard
                .FirstOrDefaultAsync(m => m.Id == id);
            if (creditCard == null)
            {
                return NotFound();
            }

            return View(creditCard);
        }

        // GET: CreditCards/Create 
        public IActionResult Create()
        {
            return View();
        }

        // POST: CreditCards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CardNumber,CardName,CardCvv,CardType,CardExpDate")] CreditCard creditCard)
        {
            string errorMsg = string.Empty;
            if (ModelState.IsValid)
            {
                bool isValidFlag = false;

                if (Luhn.CheckLuhn(creditCard.CardNumber))
                    if (!(_context.CreditCard?.Any(e => e.CardNumber == creditCard.CardNumber)).GetValueOrDefault())
                        isValidFlag = true;
                    else
                        errorMsg = "Credit card Number already exist";
                else
                    errorMsg = "Credit card Number not valid";

                if (isValidFlag)
                {
                    _context.Add(new CreditCard(creditCard.Id, creditCard.CardNumber, creditCard.CardName, creditCard.CardCvv, creditCard.CardNumber.CreditCardBrandName(), creditCard.CardExpDate));
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            ModelState.AddModelError(string.Empty, errorMsg);
            return View(creditCard);
        }

        // GET: CreditCards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CreditCard == null)
            {
                return NotFound();
            }

            var creditCard = await _context.CreditCard.FindAsync(id);
            if (creditCard == null)
            {
                return NotFound();
            }
            return View(creditCard);
        }

        // POST: CreditCards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CardNumber,CardName,CardCvv,CardType,CardExpDate")] CreditCard creditCard)
        {
            string errorMsg = string.Empty;
            if (id != creditCard.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    bool isValidFlag = false;
                    if (Luhn.CheckLuhn(creditCard.CardNumber))
                        if (!(_context.CreditCard?.Any(e => e.CardNumber == creditCard.CardNumber && e.Id != creditCard.Id)).GetValueOrDefault())
                            isValidFlag = true;
                        else
                            errorMsg = "Credit card Number already exist";
                    else
                        errorMsg = "Credit card Number not valid";

                    if (isValidFlag)
                    {
                        _context.Update(new CreditCard(creditCard.Id, creditCard.CardNumber, creditCard.CardName, creditCard.CardCvv, creditCard.CardNumber.CreditCardBrandName(), creditCard.CardExpDate));
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, errorMsg);
                        return View(creditCard);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CreditCardExists(creditCard.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError(string.Empty, errorMsg);
            return View(creditCard);
        }

        // GET: CreditCards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CreditCard == null)
            {
                return NotFound();
            }

            var creditCard = await _context.CreditCard
                .FirstOrDefaultAsync(m => m.Id == id);
            if (creditCard == null)
            {
                return NotFound();
            }

            return View(creditCard);
        }

        // POST: CreditCards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CreditCard == null)
            {
                return Problem("Entity set 'CreditCardsContext.CreditCard'  is null.");
            }
            var creditCard = await _context.CreditCard.FindAsync(id);
            if (creditCard != null)
            {
                _context.CreditCard.Remove(creditCard);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CreditCardExists(int id)
        {
            return (_context.CreditCard?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CreditCards</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-Flaty.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CreditCards.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CreditCards</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreditCards" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreditCards" asp-action="Create">Add Card</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreditCards" asp-action="Index">View Cards</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CreditCards - <a asp-area="" asp-controller="CreditCards" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>